// Type definitions for aws-sdk - Amazon Inspector
// Project: https://github.com/aws/aws-sdk-js
// Definitions by: https://github.com/ingenieux/aws-sdk-typescript
// GENERATED CODE - DO NOT EDIT

// COMMENTED <reference path="./aws-sdk.d.ts" />

declare module "aws-sdk" {

  /**
    * apiVersion: 2015-08-18
    * endpointPrefix: inspector
    * serviceAbbreviation: 
    * signatureVersion: v4
    * protocol: json
    *
    * Amazon InspectorAmazon Inspector enables you to analyze the behavior of the
 applications you run in AWS and to identify potential security issues. For more
 information, see Amazon Inspector User Guide
 [https://docs.aws.amazon.com/inspector/latest/userguide/inspector_introduction.html] 
 .
    *
    */
  export class Inspector extends Service {
    constructor(options?: any);
    endpoint: Endpoint;
    /**
     * Assigns attributes (key and value pair) to the findings specified by the
findings&#x27; ARNs.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    addAttributesToFindings(params: Inspector.AddAttributesToFindingsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.AddAttributesToFindingsResponse | any) => void): Request;
    /**
     * Attaches the rules package specified by the rules package ARN to the assessment
specified by the assessment ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    attachAssessmentAndRulesPackage(params: Inspector.AttachAssessmentAndRulesPackageRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.AttachAssessmentAndRulesPackageResponse | any) => void): Request;
    /**
     * Creates a new application using the resource group ARN generated by 
CreateResourceGroup . You can create up to 50 applications per AWS account. You
can run up to 500 concurrent agents per AWS account. For more information, see 
Inspector Applications.
[https://docs.aws.amazon.com/inspector/latest/userguide//inspector_applications.html]
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    createApplication(params: Inspector.CreateApplicationRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.CreateApplicationResponse | any) => void): Request;
    /**
     * Creates an assessment for the application specified by the application ARN. You
can create up to 500 assessments per AWS account.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    createAssessment(params: Inspector.CreateAssessmentRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.CreateAssessmentResponse | any) => void): Request;
    /**
     * Creates a resource group using the specified set of tags (key and value pairs)
that are used to select the EC2 instances to be included in an Inspector
application. The created resource group is then used to create an Inspector
application.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     */
    createResourceGroup(params: Inspector.CreateResourceGroupRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | any, data: Inspector.CreateResourceGroupResponse | any) => void): Request;
    /**
     * Deletes the application specified by the application ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error OperationInProgressException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    deleteApplication(params: Inspector.DeleteApplicationRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.OperationInProgressException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.DeleteApplicationResponse | any) => void): Request;
    /**
     * Deletes the assessment specified by the assessment ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error OperationInProgressException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    deleteAssessment(params: Inspector.DeleteAssessmentRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.OperationInProgressException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.DeleteAssessmentResponse | any) => void): Request;
    /**
     * Deletes the assessment run specified by the run ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    deleteRun(params: Inspector.DeleteRunRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.DeleteRunResponse | any) => void): Request;
    /**
     * Describes the application specified by the application ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    describeApplication(params: Inspector.DescribeApplicationRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.DescribeApplicationResponse | any) => void): Request;
    /**
     * Describes the assessment specified by the assessment ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    describeAssessment(params: Inspector.DescribeAssessmentRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.DescribeAssessmentResponse | any) => void): Request;
    /**
     * Describes the IAM role that enables Inspector to access your AWS account.
     *
     * @error InternalException   
     * @error AccessDeniedException   
     */
    describeCrossAccountAccessRole(callback?: (err: Inspector.InternalException | Inspector.AccessDeniedException | any, data: Inspector.DescribeCrossAccountAccessRoleResponse | any) => void): Request;
    /**
     * Describes the finding specified by the finding ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    describeFinding(params: Inspector.DescribeFindingRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.DescribeFindingResponse | any) => void): Request;
    /**
     * Describes the resource group specified by the resource group ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    describeResourceGroup(params: Inspector.DescribeResourceGroupRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.DescribeResourceGroupResponse | any) => void): Request;
    /**
     * Describes the rules package specified by the rules package ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    describeRulesPackage(params: Inspector.DescribeRulesPackageRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.DescribeRulesPackageResponse | any) => void): Request;
    /**
     * Describes the assessment run specified by the run ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    describeRun(params: Inspector.DescribeRunRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.DescribeRunResponse | any) => void): Request;
    /**
     * Detaches the rules package specified by the rules package ARN from the
assessment specified by the assessment ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    detachAssessmentAndRulesPackage(params: Inspector.DetachAssessmentAndRulesPackageRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.DetachAssessmentAndRulesPackageResponse | any) => void): Request;
    /**
     * Returns the metadata about the telemetry (application behavioral data) for the
assessment specified by the assessment ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    getAssessmentTelemetry(params: Inspector.GetAssessmentTelemetryRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.GetAssessmentTelemetryResponse | any) => void): Request;
    /**
     * Lists the ARNs of the applications within this AWS account. For more information
about applications, see Inspector Applications
[https://docs.aws.amazon.com/inspector/latest/userguide//inspector_applications.html] 
.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     */
    listApplications(params: Inspector.ListApplicationsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | any, data: Inspector.ListApplicationsResponse | any) => void): Request;
    /**
     * Lists the agents of the assessment specified by the assessment ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    listAssessmentAgents(params: Inspector.ListAssessmentAgentsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.ListAssessmentAgentsResponse | any) => void): Request;
    /**
     * Lists the assessments corresponding to applications specified by the
applications&#x27; ARNs.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    listAssessments(params: Inspector.ListAssessmentsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.ListAssessmentsResponse | any) => void): Request;
    /**
     * Lists the assessments attached to the rules package specified by the rules
package ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    listAttachedAssessments(params: Inspector.ListAttachedAssessmentsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.ListAttachedAssessmentsResponse | any) => void): Request;
    /**
     * Lists the rules packages attached to the assessment specified by the assessment
ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    listAttachedRulesPackages(params: Inspector.ListAttachedRulesPackagesRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.ListAttachedRulesPackagesResponse | any) => void): Request;
    /**
     * Lists findings generated by the assessment run specified by the run ARNs.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    listFindings(params: Inspector.ListFindingsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.ListFindingsResponse | any) => void): Request;
    /**
     * Lists all available Inspector rules packages.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     */
    listRulesPackages(params: Inspector.ListRulesPackagesRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | any, data: Inspector.ListRulesPackagesResponse | any) => void): Request;
    /**
     * Lists the assessment runs associated with the assessments specified by the
assessment ARNs.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    listRuns(params: Inspector.ListRunsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.ListRunsResponse | any) => void): Request;
    /**
     * Lists all tags associated with a resource.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    listTagsForResource(params: Inspector.ListTagsForResourceRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.ListTagsForResourceResponse | any) => void): Request;
    /**
     * Translates a textual identifier into a user-readable text in a specified locale.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    localizeText(params: Inspector.LocalizeTextRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.LocalizeTextResponse | any) => void): Request;
    /**
     * Previews the agents installed on the EC2 instances that are included in the
application created with the specified resource group.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     * @error InvalidCrossAccountRoleException   
     */
    previewAgentsForResourceGroup(params: Inspector.PreviewAgentsForResourceGroupRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | Inspector.InvalidCrossAccountRoleException | any, data: Inspector.PreviewAgentsForResourceGroupResponse | any) => void): Request;
    /**
     * Register the role that Inspector uses to list your EC2 instances during the
assessment.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error InvalidCrossAccountRoleException   
     */
    registerCrossAccountAccessRole(params: Inspector.RegisterCrossAccountAccessRoleRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.InvalidCrossAccountRoleException | any, data: Inspector.RegisterCrossAccountAccessRoleResponse | any) => void): Request;
    /**
     * Removes the entire attribute (key and value pair) from the findings specified by
the finding ARNs where an attribute with the specified key exists.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    removeAttributesFromFindings(params: Inspector.RemoveAttributesFromFindingsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.RemoveAttributesFromFindingsResponse | any) => void): Request;
    /**
     * Starts the analysis of the application’s behavior against selected rule packages
for the assessment specified by the assessment ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    runAssessment(params: Inspector.RunAssessmentRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.RunAssessmentResponse | any) => void): Request;
    /**
     * Sets tags (key and value pairs) to the assessment specified by the assessment
ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    setTagsForResource(params: Inspector.SetTagsForResourceRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.SetTagsForResourceResponse | any) => void): Request;
    /**
     * Starts data collection for the assessment specified by the assessment ARN. For
this API to function properly, you must not exceed the limit of running up to
500 concurrent agents per AWS account.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     * @error InvalidCrossAccountRoleException   
     */
    startDataCollection(params: Inspector.StartDataCollectionRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | Inspector.InvalidCrossAccountRoleException | any, data: Inspector.StartDataCollectionResponse | any) => void): Request;
    /**
     * Stop data collection for the assessment specified by the assessment ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    stopDataCollection(params: Inspector.StopDataCollectionRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.StopDataCollectionResponse | any) => void): Request;
    /**
     * Updates application specified by the application ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    updateApplication(params: Inspector.UpdateApplicationRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.UpdateApplicationResponse | any) => void): Request;
    /**
     * Updates the assessment specified by the assessment ARN.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    updateAssessment(params: Inspector.UpdateAssessmentRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.UpdateAssessmentResponse | any) => void): Request;

  }

  export module Inspector {

    export type AgentHealth = string;

    export type AgentHealthCode = string;

    export type AgentHealthDetails = string;

    export type AgentHealthList = AgentHealth[];

    export type AgentId = string;

    export type AgentList = Agent[];

    export type AgentPreviewList = AgentPreview[];

    export type Arn = string;

    export type ArnList = Arn[];

    export type AssessmentState = string;

    export type AssessmentStateList = AssessmentState[];

    export type AttributeKey = string;

    export type AttributeKeyList = AttributeKey[];

    export type AttributeList = Attribute[];

    export type AttributeValue = string;

    export type AutoScalingGroup = string;

    export type AwsAccount = string;

    export type Bool = boolean;

    export type Duration = number;

    export type FailureMessage = string;

    export type Integer = number;

    export type Locale = string;

    export type LocalizedFacility = string;

    export type LocalizedTextId = string;

    export type LocalizedTextList = LocalizedText[];

    export type Long = number;

    export type Message = string;

    export type MessageType = string;

    export type MessageTypeTelemetryList = MessageTypeTelemetry[];

    export type Name = string;

    export type NameList = Name[];

    export type NamePattern = string;

    export type NamePatternList = NamePattern[];

    export type PaginationToken = string;

    export type ParameterList = Parameter[];

    export type ParameterName = string;

    export type ParameterValue = string;

    export type ResourceGroupTags = string;

    export type RunState = string;

    export type RunStateList = RunState[];

    export type Severity = string;

    export type SeverityList = Severity[];

    export type TagKey = string;

    export type TagList = Tag[];

    export type TagValue = string;

    export type TelemetryList = Telemetry[];

    export type TelemetryStatus = string;

    export type Text = string;

    export type TextList = Text[];

    export type Timestamp = number;

    export type Version = string;

    export interface AccessDeniedException {
    }
    export interface AddAttributesToFindingsRequest {
      /** The ARNs specifying the findings that you want to assign attributes to. **/
      findingArns?: ArnList;
      /** The array of attributes that you want to assign to specified findings. **/
      attributes?: AttributeList;
    }
    export interface AddAttributesToFindingsResponse {
      /** Confirmation details of the action performed. **/
      message?: Message;
    }
    export interface Agent {
      /** The EC2 instance ID where the agent is installed. **/
      agentId?: AgentId;
      /** The ARN of the assessment that is associated with the agent. **/
      assessmentArn?: Arn;
      /** The current health state of the agent. Values can be set to HEALTHY or UNHEALTHY 
. **/
      agentHealth?: AgentHealth;
      /** The detailed health state of the agent. Values can be set to RUNNING , HEALTHY , 
UNHEALTHY , UNKNOWN , BLACKLISTED , SHUTDOWN , THROTTLED . **/
      agentHealthCode?: AgentHealthCode;
      /** The description for the agent health code. **/
      agentHealthDetails?: AgentHealthDetails;
      /** This data type property is currently not used. **/
      autoScalingGroup?: AutoScalingGroup;
      /** AWS account of the EC2 instance where the agent is installed. **/
      accountId?: AwsAccount;
      /** The Inspector application data metrics collected by the agent. **/
      telemetry?: TelemetryList;
    }
    export interface AgentPreview {
      /** The id of the EC2 instance where the agent is intalled. **/
      agentId?: AgentId;
      /** The autoscaling group for the EC2 instance where the agent is installed. **/
      autoScalingGroup?: AutoScalingGroup;
    }
    export interface AgentsFilter {
      /** For a record to match a filter, the value specified for this data type property
must be the exact match of the value of the agentHealth property of the Agent 
data type. **/
      agentHealthList?: AgentHealthList;
    }
    export interface Application {
      /** The ARN specifying the Inspector application. **/
      applicationArn?: Arn;
      /** The name of the Inspector application. **/
      applicationName?: Name;
      /** The ARN specifying the resource group that is associated with the application. **/
      resourceGroupArn?: Arn;
    }
    export interface ApplicationsFilter {
      /** For a record to match a filter, an explicit value or a string containing a
wildcard specified for this data type property must match the value of the 
applicationName property of the Application data type. **/
      applicationNamePatterns?: NamePatternList;
    }
    export interface Assessment {
      /** The ARN of the assessment. **/
      assessmentArn?: Arn;
      /** The name of the assessment. **/
      assessmentName?: Name;
      /** The ARN of the application that corresponds to this assessment. **/
      applicationArn?: Arn;
      /** The state of the assessment. Values can be set to Created , Collecting Data , 
Stopping , and Completed . **/
      assessmentState?: AssessmentState;
      /** This data type property is not currently used. **/
      failureMessage?: FailureMessage;
      /** Boolean value (true or false) specifying whether the data collection process is
completed. **/
      dataCollected?: Bool;
      /** The assessment start time. **/
      startTime?: Timestamp;
      /** The assessment end time. **/
      endTime?: Timestamp;
      /** The assessment duration in seconds. The default value is 3600 seconds (one
hour). The maximum value is 86400 seconds (one day). **/
      durationInSeconds?: Duration;
      /** The user-defined attributes that are assigned to every generated finding. **/
      userAttributesForFindings?: AttributeList;
    }
    export interface AssessmentsFilter {
      /** For a record to match a filter, an explicit value or a string containing a
wildcard specified for this data type property must match the value of the 
assessmentName property of the Assessment data type. **/
      assessmentNamePatterns?: NamePatternList;
      /** For a record to match a filter, the value specified for this data type property
must be the exact match of the value of the assessmentState property of the 
Assessment data type. **/
      assessmentStates?: AssessmentStateList;
      /** For a record to match a filter, the value specified for this data type property
must be the exact match of the value of the dataCollected property of the 
Assessment data type. **/
      dataCollected?: Bool;
      /** For a record to match a filter, the value specified for this data type property
must inclusively match any value between the specified minimum and maximum
values of the startTime property of the Assessment data type. **/
      startTimeRange?: TimestampRange;
      /** For a record to match a filter, the value specified for this data type property
must inclusively match any value between the specified minimum and maximum
values of the endTime property of the Assessment data type. **/
      endTimeRange?: TimestampRange;
      /** For a record to match a filter, the value specified for this data type property
must inclusively match any value between the specified minimum and maximum
values of the durationInSeconds property of the Assessment data type. **/
      durationRange?: DurationRange;
    }
    export interface AttachAssessmentAndRulesPackageRequest {
      /** The ARN specifying the assessment to which you want to attach a rules package. **/
      assessmentArn?: Arn;
      /** The ARN specifying the rules package that you want to attach to the assessment. **/
      rulesPackageArn?: Arn;
    }
    export interface AttachAssessmentAndRulesPackageResponse {
      /** Confirmation details of the action performed. **/
      message?: Message;
    }
    export interface Attribute {
      /** The attribute key. **/
      key?: AttributeKey;
      /** The value assigned to the attribute key. **/
      value?: AttributeValue;
    }
    export interface CreateApplicationRequest {
      /** The user-defined name identifying the application that you want to create. The
name must be unique within the AWS account. **/
      applicationName?: Name;
      /** The ARN specifying the resource group that is used to create the application. **/
      resourceGroupArn?: Arn;
    }
    export interface CreateApplicationResponse {
      /** The ARN specifying the application that is created. **/
      applicationArn?: Arn;
    }
    export interface CreateAssessmentRequest {
      /** The ARN specifying the application for which you want to create an assessment. **/
      applicationArn?: Arn;
      /** The user-defined name identifying the assessment that you want to create. You
can create several assessments for an application. The names of the assessments
corresponding to a particular application must be unique. **/
      assessmentName?: Name;
      /** The duration of the assessment in seconds. The default value is 3600 seconds
(one hour). The maximum value is 86400 seconds (one day). **/
      durationInSeconds?: Duration;
      /** The user-defined attributes that are assigned to every finding generated by
running this assessment. **/
      userAttributesForFindings?: AttributeList;
    }
    export interface CreateAssessmentResponse {
      /** The ARN specifying the assessment that is created. **/
      assessmentArn?: Arn;
    }
    export interface CreateResourceGroupRequest {
      /** A collection of keys and an array of possible values in JSON format.

For example, [{ &quot;key1&quot; : [&quot;Value1&quot;,&quot;Value2&quot;]},{&quot;Key2&quot;: [&quot;Value3&quot;]}] **/
      resourceGroupTags?: ResourceGroupTags;
    }
    export interface CreateResourceGroupResponse {
      /** The ARN specifying the resource group that is created. **/
      resourceGroupArn?: Arn;
    }
    export interface DeleteApplicationRequest {
      /** The ARN specifying the application that you want to delete. **/
      applicationArn?: Arn;
    }
    export interface DeleteApplicationResponse {
      /** Confirmation details of the action performed. **/
      message?: Message;
    }
    export interface DeleteAssessmentRequest {
      /** The ARN specifying the assessment that you want to delete. **/
      assessmentArn?: Arn;
    }
    export interface DeleteAssessmentResponse {
      /** Confirmation details of the action performed. **/
      message?: Message;
    }
    export interface DeleteRunRequest {
      /** The ARN specifying the assessment run that you want to delete. **/
      runArn?: Arn;
    }
    export interface DeleteRunResponse {
      /** Confirmation details of the action performed. **/
      message?: Message;
    }
    export interface DescribeApplicationRequest {
      /** The ARN specifying the application that you want to describe. **/
      applicationArn?: Arn;
    }
    export interface DescribeApplicationResponse {
      /** Information about the application. **/
      application?: Application;
    }
    export interface DescribeAssessmentRequest {
      /** The ARN specifying the assessment that you want to describe. **/
      assessmentArn?: Arn;
    }
    export interface DescribeAssessmentResponse {
      /** Information about the assessment. **/
      assessment?: Assessment;
    }
    export interface DescribeCrossAccountAccessRoleResponse {
      /** The ARN specifying the IAM role that Inspector uses to access your AWS account. **/
      roleArn?: Arn;
      /** A Boolean value that specifies whether the IAM role has the necessary policies
attached to enable Inspector to access your AWS account. **/
      valid?: Bool;
    }
    export interface DescribeFindingRequest {
      /** The ARN specifying the finding that you want to describe. **/
      findingArn?: Arn;
    }
    export interface DescribeFindingResponse {
      /** Information about the finding. **/
      finding?: Finding;
    }
    export interface DescribeResourceGroupRequest {
      /** The ARN specifying the resource group that you want to describe. **/
      resourceGroupArn?: Arn;
    }
    export interface DescribeResourceGroupResponse {
      /** Information about the resource group. **/
      resourceGroup?: ResourceGroup;
    }
    export interface DescribeRulesPackageRequest {
      /** The ARN specifying the rules package that you want to describe. **/
      rulesPackageArn?: Arn;
    }
    export interface DescribeRulesPackageResponse {
      /** Information about the rules package. **/
      rulesPackage?: RulesPackage;
    }
    export interface DescribeRunRequest {
      /** The ARN specifying the assessment run that you want to describe. **/
      runArn?: Arn;
    }
    export interface DescribeRunResponse {
      /** Information about the assessment run. **/
      run?: Run;
    }
    export interface DetachAssessmentAndRulesPackageRequest {
      /** The ARN specifying the assessment from which you want to detach a rules package. **/
      assessmentArn?: Arn;
      /** The ARN specifying the rules package that you want to detach from the
assessment. **/
      rulesPackageArn?: Arn;
    }
    export interface DetachAssessmentAndRulesPackageResponse {
      /** Confirmation details of the action performed. **/
      message?: Message;
    }
    export interface DurationRange {
      /** The minimum value of the duration range. Must be greater than zero. **/
      minimum?: Duration;
      /** The maximum value of the duration range. Must be less than or equal to 604800
seconds (1 week). **/
      maximum?: Duration;
    }
    export interface Finding {
      /** The ARN specifying the finding. **/
      findingArn?: Arn;
      /** The ARN of the assessment run that generated the finding. **/
      runArn?: Arn;
      /** The ARN of the rules package that is used to generate the finding. **/
      rulesPackageArn?: Arn;
      /** The rule name that is used to generate the finding. **/
      ruleName?: Name;
      /** The EC2 instance ID where the agent is installed that is used during the
assessment that generates the finding. **/
      agentId?: AgentId;
      /** The autoscaling group of the EC2 instance where the agent is installed that is
used during the assessment that generates the finding. **/
      autoScalingGroup?: AutoScalingGroup;
      /** The finding severity. Values can be set to High , Medium , Low , and 
Informational . **/
      severity?: Severity;
      /** A short description that identifies the finding. **/
      finding?: LocalizedText;
      /** The description of the finding. **/
      description?: LocalizedText;
      /** The recommendation for the finding. **/
      recommendation?: LocalizedText;
      /** The system-defined attributes for the finding. **/
      attributes?: AttributeList;
      /** The user-defined attributes that are assigned to the finding. **/
      userAttributes?: AttributeList;
    }
    export interface FindingsFilter {
      /** For a record to match a filter, the value specified for this data type property
must be the exact match of the value of the rulesPackageArn property of the 
Finding data type. **/
      rulesPackageArns?: ArnList;
      /** For a record to match a filter, the value specified for this data type property
must be the exact match of the value of the ruleName property of the Finding 
data type. **/
      ruleNames?: NameList;
      /** For a record to match a filter, the value specified for this data type property
must be the exact match of the value of the severity property of the Finding 
data type. **/
      severities?: SeverityList;
      /** For a record to match a filter, the value specified for this data type property
must be the exact match of the value of the attributes property of the Finding 
data type. **/
      attributes?: AttributeList;
      /** For a record to match a filter, the value specified for this data type property
must be the exact match of the value of the userAttributes property of the 
Finding data type. **/
      userAttributes?: AttributeList;
    }
    export interface GetAssessmentTelemetryRequest {
      /** The ARN specifying the assessment the telemetry of which you want to obtain. **/
      assessmentArn?: Arn;
    }
    export interface GetAssessmentTelemetryResponse {
      /** Telemetry details. **/
      telemetry?: TelemetryList;
    }
    export interface InternalException {
    }
    export interface InvalidCrossAccountRoleException {
    }
    export interface InvalidInputException {
    }
    export interface ListApplicationsRequest {
      /** You can use this parameter to specify a subset of data to be included in the
action&#x27;s response.

For a record to match a filter, all specified filter attributes must match. When
multiple values are specified for a filter attribute, any of the values can
match. **/
      filter?: ApplicationsFilter;
      /** You can use this parameter when paginating results. Set the value of this
parameter to &#x27;null&#x27; on your first call to the ListApplications action.
Subsequent calls to the action fill nextToken in the request with the value of 
NextToken from previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: Integer;
    }
    export interface ListApplicationsResponse {
      /** A list of ARNs specifying the applications returned by the action. **/
      applicationArnList?: ArnList;
      /** When a response is generated, if there is more data to be listed, this parameter
is present in the response and contains the value to use for the nextToken 
parameter in a subsequent pagination request. If there is no more data to be
listed, this parameter is set to &#x27;null&#x27;. **/
      nextToken?: PaginationToken;
    }
    export interface ListAssessmentAgentsRequest {
      /** The ARN specifying the assessment whose agents you want to list. **/
      assessmentArn?: Arn;
      /** You can use this parameter to specify a subset of data to be included in the
action&#x27;s response.

For a record to match a filter, all specified filter attributes must match. When
multiple values are specified for a filter attribute, any of the values can
match. **/
      filter?: AgentsFilter;
      /** You can use this parameter when paginating results. Set the value of this
parameter to &#x27;null&#x27; on your first call to the ListAssessmentAgents action.
Subsequent calls to the action fill nextToken in the request with the value of 
NextToken from previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: Integer;
    }
    export interface ListAssessmentAgentsResponse {
      /** A list of ARNs specifying the agents returned by the action. **/
      agentList?: AgentList;
      /** When a response is generated, if there is more data to be listed, this parameter
is present in the response and contains the value to use for the nextToken 
parameter in a subsequent pagination request. If there is no more data to be
listed, this parameter is set to &#x27;null&#x27;. **/
      nextToken?: PaginationToken;
    }
    export interface ListAssessmentsRequest {
      /** A list of ARNs specifying the applications the assessments of which you want to
list. **/
      applicationArns?: ArnList;
      /** You can use this parameter to specify a subset of data to be included in the
action&#x27;s response.

For a record to match a filter, all specified filter attributes must match. When
multiple values are specified for a filter attribute, any of the values can
match. **/
      filter?: AssessmentsFilter;
      /** You can use this parameter when paginating results. Set the value of this
parameter to &#x27;null&#x27; on your first call to the ListAssessments action. Subsequent
calls to the action fill nextToken in the request with the value of NextToken 
from previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: Integer;
    }
    export interface ListAssessmentsResponse {
      /** A list of ARNs specifying the assessments returned by the action. **/
      assessmentArnList?: ArnList;
      /** When a response is generated, if there is more data to be listed, this parameter
is present in the response and contains the value to use for the nextToken 
parameter in a subsequent pagination request. If there is no more data to be
listed, this parameter is set to &#x27;null&#x27;. **/
      nextToken?: PaginationToken;
    }
    export interface ListAttachedAssessmentsRequest {
      /** The ARN specifying the rules package whose assessments you want to list. **/
      rulesPackageArn?: Arn;
      /** You can use this parameter to specify a subset of data to be included in the
action&#x27;s response.

For a record to match a filter, all specified filter attributes must match. When
multiple values are specified for a filter attribute, any of the values can
match. **/
      filter?: AssessmentsFilter;
      /** You can use this parameter when paginating results. Set the value of this
parameter to &#x27;null&#x27; on your first call to the ListAttachedAssessments action.
Subsequent calls to the action fill nextToken in the request with the value of 
NextToken from previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: Integer;
    }
    export interface ListAttachedAssessmentsResponse {
      /** A list of ARNs specifying the assessments returned by the action. **/
      assessmentArnList?: ArnList;
      /** When a response is generated, if there is more data to be listed, this parameter
is present in the response and contains the value to use for the nextToken 
parameter in a subsequent pagination request. If there is no more data to be
listed, this parameter is set to &#x27;null&#x27;. **/
      nextToken?: PaginationToken;
    }
    export interface ListAttachedRulesPackagesRequest {
      /** The ARN specifying the assessment whose rules packages you want to list. **/
      assessmentArn?: Arn;
      /** You can use this parameter when paginating results. Set the value of this
parameter to &#x27;null&#x27; on your first call to the ListAttachedRulesPackages action.
Subsequent calls to the action fill nextToken in the request with the value of 
NextToken from previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: Integer;
    }
    export interface ListAttachedRulesPackagesResponse {
      /** A list of ARNs specifying the rules packages returned by the action. **/
      rulesPackageArnList?: ArnList;
      /** When a response is generated, if there is more data to be listed, this parameter
is present in the response and contains the value to use for the nextToken 
parameter in a subsequent pagination request. If there is no more data to be
listed, this parameter is set to &#x27;null&#x27;. **/
      nextToken?: PaginationToken;
    }
    export interface ListFindingsRequest {
      /** The ARNs of the assessment runs that generate the findings that you want to
list. **/
      runArns?: ArnList;
      /** You can use this parameter to specify a subset of data to be included in the
action&#x27;s response.

For a record to match a filter, all specified filter attributes must match. When
multiple values are specified for a filter attribute, any of the values can
match. **/
      filter?: FindingsFilter;
      /** You can use this parameter when paginating results. Set the value of this
parameter to &#x27;null&#x27; on your first call to the ListFindings action. Subsequent
calls to the action fill nextToken in the request with the value of NextToken 
from previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: Integer;
    }
    export interface ListFindingsResponse {
      /** A list of ARNs specifying the findings returned by the action. **/
      findingArnList?: ArnList;
      /** When a response is generated, if there is more data to be listed, this parameter
is present in the response and contains the value to use for the nextToken 
parameter in a subsequent pagination request. If there is no more data to be
listed, this parameter is set to &#x27;null&#x27;. **/
      nextToken?: PaginationToken;
    }
    export interface ListRulesPackagesRequest {
      /** You can use this parameter when paginating results. Set the value of this
parameter to &#x27;null&#x27; on your first call to the ListRulesPackages action.
Subsequent calls to the action fill nextToken in the request with the value of 
NextToken from previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: Integer;
    }
    export interface ListRulesPackagesResponse {
      /** The list of ARNs specifying the rules packages returned by the action. **/
      rulesPackageArnList?: ArnList;
      /** When a response is generated, if there is more data to be listed, this parameter
is present in the response and contains the value to use for the nextToken 
parameter in a subsequent pagination request. If there is no more data to be
listed, this parameter is set to &#x27;null&#x27;. **/
      nextToken?: PaginationToken;
    }
    export interface ListRunsRequest {
      /** The ARNs specifying the assessments whose runs you want to list. **/
      assessmentArns?: ArnList;
      /** You can use this parameter to specify a subset of data to be included in the
action&#x27;s response.

For a record to match a filter, all specified filter attributes must match. When
multiple values are specified for a filter attribute, any of the values can
match. **/
      filter?: RunsFilter;
      /** You can use this parameter when paginating results. Set the value of this
parameter to &#x27;null&#x27; on your first call to the ListRuns action. Subsequent calls
to the action fill nextToken in the request with the value of NextToken from
previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: Integer;
    }
    export interface ListRunsResponse {
      /** A list of ARNs specifying the assessment runs returned by the action. **/
      runArnList?: ArnList;
      /** When a response is generated, if there is more data to be listed, this parameter
is present in the response and contains the value to use for the nextToken 
parameter in a subsequent pagination request. If there is no more data to be
listed, this parameter is set to &#x27;null&#x27;. **/
      nextToken?: PaginationToken;
    }
    export interface ListTagsForResourceRequest {
      /** The ARN specifying the resource whose tags you want to list. **/
      resourceArn?: Arn;
    }
    export interface ListTagsForResourceResponse {
      /** A collection of key and value pairs. **/
      tagList?: TagList;
    }
    export interface LocalizeTextRequest {
      /** A list of textual identifiers. **/
      localizedTexts?: LocalizedTextList;
      /** The locale that you want to translate a textual identifier into. **/
      locale?: Locale;
    }
    export interface LocalizeTextResponse {
      /** Confirmation details of the action performed. **/
      message?: Message;
      /** The resulting list of user-readable texts. **/
      results?: TextList;
    }
    export interface LocalizedText {
      /** The facility and id properties of the LocalizedTextKey data type. **/
      key?: LocalizedTextKey;
      /** Values for the dynamic elements of the string specified by the textual
identifier. **/
      parameters?: ParameterList;
    }
    export interface LocalizedTextKey {
      /** The module response source of the text. **/
      facility?: LocalizedFacility;
      /** Part of the module response source of the text. **/
      id?: LocalizedTextId;
    }
    export interface MessageTypeTelemetry {
      /** A specific type of behavioral data that is collected by the agent. **/
      messageType?: MessageType;
      /** The number of times that the behavioral data is collected by the agent during an
assessment. **/
      count?: Long;
      /** The total size of the behavioral data that is collected by the agent during an
assessment. **/
      dataSize?: Long;
    }
    export interface NoSuchEntityException {
    }
    export interface OperationInProgressException {
    }
    export interface Parameter {
      /** The name of the variable that is being replaced. **/
      name?: ParameterName;
      /** The value assigned to the variable that is being replaced. **/
      value?: ParameterValue;
    }
    export interface PreviewAgentsForResourceGroupRequest {
      /** The ARN of the resource group that is used to create an application. **/
      resourceGroupArn?: Arn;
      /** You can use this parameter when paginating results. Set the value of this
parameter to &#x27;null&#x27; on your first call to the PreviewAgentsForResourceGroup 
action. Subsequent calls to the action fill nextToken in the request with the
value of NextToken from previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: Integer;
    }
    export interface PreviewAgentsForResourceGroupResponse {
      /** The resulting list of agents. **/
      agentPreviewList?: AgentPreviewList;
      /** When a response is generated, if there is more data to be listed, this parameter
is present in the response and contains the value to use for the nextToken 
parameter in a subsequent pagination request. If there is no more data to be
listed, this parameter is set to &#x27;null&#x27;. **/
      nextToken?: PaginationToken;
    }
    export interface RegisterCrossAccountAccessRoleRequest {
      /** The ARN of the IAM role that Inspector uses to list your EC2 instances during
the assessment. **/
      roleArn?: Arn;
    }
    export interface RegisterCrossAccountAccessRoleResponse {
      /** Confirmation details of the action performed. **/
      message?: Message;
    }
    export interface RemoveAttributesFromFindingsRequest {
      /** The ARNs specifying the findings that you want to remove attributes from. **/
      findingArns?: ArnList;
      /** The array of attribute keys that you want to remove from specified findings. **/
      attributeKeys?: AttributeKeyList;
    }
    export interface RemoveAttributesFromFindingsResponse {
      /** Confirmation details of the action performed. **/
      message?: Message;
    }
    export interface ResourceGroup {
      /** The ARN of the resource group. **/
      resourceGroupArn?: Arn;
      /** The tags (key and value pairs) of the resource group.

This data type property is used in the CreateResourceGroup action.

A collection of keys and an array of possible values in JSON format.

For example, [{ &quot;key1&quot; : [&quot;Value1&quot;,&quot;Value2&quot;]},{&quot;Key2&quot;: [&quot;Value3&quot;]}] **/
      resourceGroupTags?: ResourceGroupTags;
    }
    export interface RulesPackage {
      /** The ARN of the rules package. **/
      rulesPackageArn?: Arn;
      /** The name of the rules package. **/
      rulesPackageName?: Name;
      /** The version id of the rules package. **/
      version?: Version;
      /** The provider of the rules package. **/
      provider?: Name;
      /** The description of the rules package. **/
      description?: LocalizedText;
    }
    export interface Run {
      /** The ARN of the run. **/
      runArn?: Arn;
      /** The auto-generated name for the run. **/
      runName?: Name;
      /** The ARN of the assessment that is associated with the run. **/
      assessmentArn?: Arn;
      /** The state of the run. Values can be set to DataCollectionComplete , 
EvaluatingPolicies , EvaluatingPoliciesErrorCanRetry , Completed , Failed , 
TombStoned . **/
      runState?: RunState;
      /** Rules packages selected for the run of the assessment. **/
      rulesPackages?: ArnList;
      /** Run creation time that corresponds to the data collection completion time or
failure. **/
      creationTime?: Timestamp;
      /** Run completion time that corresponds to the rules packages evaluation completion
time or failure. **/
      completionTime?: Timestamp;
    }
    export interface RunAssessmentRequest {
      /** The ARN of the assessment that you want to run. **/
      assessmentArn?: Arn;
      /** A name specifying the run of the assessment. **/
      runName?: Name;
    }
    export interface RunAssessmentResponse {
      /** The ARN specifying the run of the assessment. **/
      runArn?: Arn;
    }
    export interface RunsFilter {
      /** For a record to match a filter, an explicit value or a string containing a
wildcard specified for this data type property must match the value of the 
runName property of the Run data type. **/
      runNamePatterns?: NamePatternList;
      /** For a record to match a filter, the value specified for this data type property
must be the exact match of the value of the runState property of the Run data
type. **/
      runStates?: RunStateList;
      /** For a record to match a filter, the value specified for this data type property
must match a list of values of the rulesPackages property of the Run data type. **/
      rulesPackages?: ArnList;
      /** For a record to match a filter, the value specified for this data type property
must inclusively match any value between the specified minimum and maximum
values of the creationTime property of the Run data type. **/
      creationTime?: TimestampRange;
      /** For a record to match a filter, the value specified for this data type property
must inclusively match any value between the specified minimum and maximum
values of the completionTime property of the Run data type. **/
      completionTime?: TimestampRange;
    }
    export interface SetTagsForResourceRequest {
      /** The ARN of the assessment that you want to set tags to. **/
      resourceArn?: Arn;
      /** A collection of key and value pairs that you want to set to an assessment. **/
      tags?: TagList;
    }
    export interface SetTagsForResourceResponse {
      /** Confirmation details of the action performed. **/
      message?: Message;
    }
    export interface StartDataCollectionRequest {
      /** The ARN of the assessment for which you want to start the data collection
process. **/
      assessmentArn?: Arn;
    }
    export interface StartDataCollectionResponse {
      /** Confirmation details of the action performed. **/
      message?: Message;
    }
    export interface StopDataCollectionRequest {
      /** The ARN of the assessment for which you want to stop the data collection
process. **/
      assessmentArn?: Arn;
    }
    export interface StopDataCollectionResponse {
      /** Confirmation details of the action performed. **/
      message?: Message;
    }
    export interface Tag {
      /** The tag key. **/
      Key?: TagKey;
      /** The value assigned to a tag key. **/
      Value?: TagValue;
    }
    export interface Telemetry {
      /** The category of the individual metrics that together constitute the telemetry
that Inspector received from the agent. **/
      status?: TelemetryStatus;
      /** Counts of individual metrics received by Inspector from the agent. **/
      messageTypeTelemetries?: MessageTypeTelemetryList;
    }
    export interface TimestampRange {
      /** The minimum value of the timestamp range. **/
      minimum?: Timestamp;
      /** The maximum value of the timestamp range. **/
      maximum?: Timestamp;
    }
    export interface UpdateApplicationRequest {
      /** Application ARN that you want to update. **/
      applicationArn?: Arn;
      /** Application name that you want to update. **/
      applicationName?: Name;
      /** The resource group ARN that you want to update. **/
      resourceGroupArn?: Arn;
    }
    export interface UpdateApplicationResponse {
      /** Confirmation details of the action performed. **/
      message?: Message;
    }
    export interface UpdateAssessmentRequest {
      /** Asessment ARN that you want to update. **/
      assessmentArn?: Arn;
      /** Assessment name that you want to update. **/
      assessmentName?: Name;
      /** Assessment duration in seconds that you want to update. The default value is
3600 seconds (one hour). The maximum value is 86400 seconds (one day). **/
      durationInSeconds?: Duration;
    }
    export interface UpdateAssessmentResponse {
      /** Confirmation details of the action performed. **/
      message?: Message;
    }
  }
}
