// Type definitions for aws-sdk - Amazon Inspector
// Project: https://github.com/aws/aws-sdk-js
// Definitions by: https://github.com/ingenieux/aws-sdk-typescript
// GENERATED CODE - DO NOT EDIT

// COMMENTED <reference path="./aws-sdk.d.ts" />

declare module "aws-sdk" {

  /**
    * apiVersion: 2016-02-16
    * endpointPrefix: inspector
    * serviceAbbreviation: 
    * signatureVersion: v4
    * protocol: json
    *
    * Amazon Inspector Amazon Inspector enables you to analyze the behavior of your
 AWS resources and to identify potential security issues. For more information,
 see Amazon Inspector User Guide
 [http://docs.aws.amazon.com/inspector/latest/userguide/inspector_introduction.html]
 .
    *
    */
  export class Inspector extends Service {
    constructor(options?: any);
    endpoint: Endpoint;
    /**
     * Assigns attributes (key and value pairs) to the findings that are specified by
the ARNs of the findings.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    addAttributesToFindings(params: Inspector.AddAttributesToFindingsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.AddAttributesToFindingsResponse | any) => void): Request<Inspector.AddAttributesToFindingsResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Creates a new assessment target using the ARN of the resource group that is
generated by CreateResourceGroup. You can create up to 50 assessment targets per
AWS account. You can run up to 500 concurrent agents per AWS account. For more
information, see Amazon Inspector Assessment Targets
[http://docs.aws.amazon.com/inspector/latest/userguide/inspector_applications.html]
.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error LimitExceededException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    createAssessmentTarget(params: Inspector.CreateAssessmentTargetRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.LimitExceededException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.CreateAssessmentTargetResponse | any) => void): Request<Inspector.CreateAssessmentTargetResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.LimitExceededException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Creates an assessment template for the assessment target that is specified by
the ARN of the assessment target.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error LimitExceededException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    createAssessmentTemplate(params: Inspector.CreateAssessmentTemplateRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.LimitExceededException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.CreateAssessmentTemplateResponse | any) => void): Request<Inspector.CreateAssessmentTemplateResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.LimitExceededException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Creates a resource group using the specified set of tags (key and value pairs)
that are used to select the EC2 instances to be included in an Amazon Inspector
assessment target. The created resource group is then used to create an Amazon
Inspector assessment target. For more information, see CreateAssessmentTarget.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error LimitExceededException   
     * @error AccessDeniedException   
     */
    createResourceGroup(params: Inspector.CreateResourceGroupRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.LimitExceededException | Inspector.AccessDeniedException | any, data: Inspector.CreateResourceGroupResponse | any) => void): Request<Inspector.CreateResourceGroupResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.LimitExceededException | Inspector.AccessDeniedException | any>;
    /**
     * Deletes the assessment run that is specified by the ARN of the assessment run.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AssessmentRunInProgressException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    deleteAssessmentRun(params: Inspector.DeleteAssessmentRunRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AssessmentRunInProgressException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: any) => void): Request<any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AssessmentRunInProgressException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Deletes the assessment target that is specified by the ARN of the assessment
target.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AssessmentRunInProgressException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    deleteAssessmentTarget(params: Inspector.DeleteAssessmentTargetRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AssessmentRunInProgressException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: any) => void): Request<any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AssessmentRunInProgressException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Deletes the assessment template that is specified by the ARN of the assessment
template.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AssessmentRunInProgressException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    deleteAssessmentTemplate(params: Inspector.DeleteAssessmentTemplateRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AssessmentRunInProgressException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: any) => void): Request<any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AssessmentRunInProgressException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Describes the assessment runs that are specified by the ARNs of the assessment
runs.
     *
     * @error InternalException   
     * @error InvalidInputException   
     */
    describeAssessmentRuns(params: Inspector.DescribeAssessmentRunsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | any, data: Inspector.DescribeAssessmentRunsResponse | any) => void): Request<Inspector.DescribeAssessmentRunsResponse | any, Inspector.InternalException | Inspector.InvalidInputException | any>;
    /**
     * Describes the assessment targets that are specified by the ARNs of the
assessment targets.
     *
     * @error InternalException   
     * @error InvalidInputException   
     */
    describeAssessmentTargets(params: Inspector.DescribeAssessmentTargetsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | any, data: Inspector.DescribeAssessmentTargetsResponse | any) => void): Request<Inspector.DescribeAssessmentTargetsResponse | any, Inspector.InternalException | Inspector.InvalidInputException | any>;
    /**
     * Describes the assessment templates that are specified by the ARNs of the
assessment templates.
     *
     * @error InternalException   
     * @error InvalidInputException   
     */
    describeAssessmentTemplates(params: Inspector.DescribeAssessmentTemplatesRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | any, data: Inspector.DescribeAssessmentTemplatesResponse | any) => void): Request<Inspector.DescribeAssessmentTemplatesResponse | any, Inspector.InternalException | Inspector.InvalidInputException | any>;
    /**
     * Describes the IAM role that enables Amazon Inspector to access your AWS account.
     *
     * @error InternalException   
     */
    describeCrossAccountAccessRole(callback?: (err: Inspector.InternalException | any, data: Inspector.DescribeCrossAccountAccessRoleResponse | any) => void): Request<Inspector.DescribeCrossAccountAccessRoleResponse | any, Inspector.InternalException | any>;
    /**
     * Describes the findings that are specified by the ARNs of the findings.
     *
     * @error InternalException   
     * @error InvalidInputException   
     */
    describeFindings(params: Inspector.DescribeFindingsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | any, data: Inspector.DescribeFindingsResponse | any) => void): Request<Inspector.DescribeFindingsResponse | any, Inspector.InternalException | Inspector.InvalidInputException | any>;
    /**
     * Describes the resource groups that are specified by the ARNs of the resource
groups.
     *
     * @error InternalException   
     * @error InvalidInputException   
     */
    describeResourceGroups(params: Inspector.DescribeResourceGroupsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | any, data: Inspector.DescribeResourceGroupsResponse | any) => void): Request<Inspector.DescribeResourceGroupsResponse | any, Inspector.InternalException | Inspector.InvalidInputException | any>;
    /**
     * Describes the rules packages that are specified by the ARNs of the rules
packages.
     *
     * @error InternalException   
     * @error InvalidInputException   
     */
    describeRulesPackages(params: Inspector.DescribeRulesPackagesRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | any, data: Inspector.DescribeRulesPackagesResponse | any) => void): Request<Inspector.DescribeRulesPackagesResponse | any, Inspector.InternalException | Inspector.InvalidInputException | any>;
    /**
     * Information about the data that is collected for the specified assessment run.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    getTelemetryMetadata(params: Inspector.GetTelemetryMetadataRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.GetTelemetryMetadataResponse | any) => void): Request<Inspector.GetTelemetryMetadataResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Lists the agents of the assessment runs that are specified by the ARNs of the
assessment runs.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    listAssessmentRunAgents(params: Inspector.ListAssessmentRunAgentsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.ListAssessmentRunAgentsResponse | any) => void): Request<Inspector.ListAssessmentRunAgentsResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Lists the assessment runs that correspond to the assessment templates that are
specified by the ARNs of the assessment templates.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    listAssessmentRuns(params: Inspector.ListAssessmentRunsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.ListAssessmentRunsResponse | any) => void): Request<Inspector.ListAssessmentRunsResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Lists the ARNs of the assessment targets within this AWS account. For more
information about assessment targets, see Amazon Inspector Assessment Targets
[http://docs.aws.amazon.com/inspector/latest/userguide/inspector_applications.html]
.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     */
    listAssessmentTargets(params: Inspector.ListAssessmentTargetsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | any, data: Inspector.ListAssessmentTargetsResponse | any) => void): Request<Inspector.ListAssessmentTargetsResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | any>;
    /**
     * Lists the assessment templates that correspond to the assessment targets that
are specified by the ARNs of the assessment targets.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    listAssessmentTemplates(params: Inspector.ListAssessmentTemplatesRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.ListAssessmentTemplatesResponse | any) => void): Request<Inspector.ListAssessmentTemplatesResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Lists all the event subscriptions for the assessment template that is specified
by the ARN of the assessment template. For more information, see 
SubscribeToEvent and UnsubscribeFromEvent.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    listEventSubscriptions(params: Inspector.ListEventSubscriptionsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.ListEventSubscriptionsResponse | any) => void): Request<Inspector.ListEventSubscriptionsResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Lists findings that are generated by the assessment runs that are specified by
the ARNs of the assessment runs.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    listFindings(params: Inspector.ListFindingsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.ListFindingsResponse | any) => void): Request<Inspector.ListFindingsResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Lists all available Amazon Inspector rules packages.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     */
    listRulesPackages(params: Inspector.ListRulesPackagesRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | any, data: Inspector.ListRulesPackagesResponse | any) => void): Request<Inspector.ListRulesPackagesResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | any>;
    /**
     * Lists all tags associated with an assessment template.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    listTagsForResource(params: Inspector.ListTagsForResourceRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.ListTagsForResourceResponse | any) => void): Request<Inspector.ListTagsForResourceResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Previews the agents installed on the EC2 instances that are part of the
specified assessment target.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     * @error InvalidCrossAccountRoleException   
     */
    previewAgents(params: Inspector.PreviewAgentsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | Inspector.InvalidCrossAccountRoleException | any, data: Inspector.PreviewAgentsResponse | any) => void): Request<Inspector.PreviewAgentsResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | Inspector.InvalidCrossAccountRoleException | any>;
    /**
     * Registers the IAM role that Amazon Inspector uses to list your EC2 instances at
the start of the assessment run or when you call the PreviewAgents action.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error InvalidCrossAccountRoleException   
     */
    registerCrossAccountAccessRole(params: Inspector.RegisterCrossAccountAccessRoleRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.InvalidCrossAccountRoleException | any, data: any) => void): Request<any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.InvalidCrossAccountRoleException | any>;
    /**
     * Removes entire attributes (key and value pairs) from the findings that are
specified by the ARNs of the findings where an attribute with the specified key
exists.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    removeAttributesFromFindings(params: Inspector.RemoveAttributesFromFindingsRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: Inspector.RemoveAttributesFromFindingsResponse | any) => void): Request<Inspector.RemoveAttributesFromFindingsResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Sets tags (key and value pairs) to the assessment template that is specified by
the ARN of the assessment template.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    setTagsForResource(params: Inspector.SetTagsForResourceRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: any) => void): Request<any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Starts the assessment run specified by the ARN of the assessment template. For
this API to function properly, you must not exceed the limit of running up to
500 concurrent agents per AWS account.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error LimitExceededException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     * @error InvalidCrossAccountRoleException   
     * @error AgentsAlreadyRunningAssessmentException   
     */
    startAssessmentRun(params: Inspector.StartAssessmentRunRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.LimitExceededException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | Inspector.InvalidCrossAccountRoleException | Inspector.AgentsAlreadyRunningAssessmentException | any, data: Inspector.StartAssessmentRunResponse | any) => void): Request<Inspector.StartAssessmentRunResponse | any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.LimitExceededException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | Inspector.InvalidCrossAccountRoleException | Inspector.AgentsAlreadyRunningAssessmentException | any>;
    /**
     * Stops the assessment run that is specified by the ARN of the assessment run.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    stopAssessmentRun(params: Inspector.StopAssessmentRunRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: any) => void): Request<any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Enables the process of sending Amazon Simple Notification Service (SNS)
notifications about a specified event to a specified SNS topic.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error LimitExceededException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    subscribeToEvent(params: Inspector.SubscribeToEventRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.LimitExceededException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: any) => void): Request<any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.LimitExceededException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Disables the process of sending Amazon Simple Notification Service (SNS)
notifications about a specified event to a specified SNS topic.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    unsubscribeFromEvent(params: Inspector.UnsubscribeFromEventRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: any) => void): Request<any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;
    /**
     * Updates the assessment target that is specified by the ARN of the assessment
target.
     *
     * @error InternalException   
     * @error InvalidInputException   
     * @error AccessDeniedException   
     * @error NoSuchEntityException   
     */
    updateAssessmentTarget(params: Inspector.UpdateAssessmentTargetRequest, callback?: (err: Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any, data: any) => void): Request<any, Inspector.InternalException | Inspector.InvalidInputException | Inspector.AccessDeniedException | Inspector.NoSuchEntityException | any>;

  }

  export module Inspector {

    export type AccessDeniedErrorCode = string;

    export type AddRemoveAttributesFindingArnList = Arn[];

    export type AgentAlreadyRunningAssessmentList = AgentAlreadyRunningAssessment[];

    export type AgentHealth = string;

    export type AgentHealthCode = string;

    export type AgentHealthCodeList = AgentHealthCode[];

    export type AgentHealthList = AgentHealth[];

    export type AgentId = string;

    export type AgentIdList = AgentId[];

    export type AgentPreviewList = AgentPreview[];

    export type AmiId = string;

    export type Arn = string;

    export type AssessmentRulesPackageArnList = Arn[];

    export type AssessmentRunAgentList = AssessmentRunAgent[];

    export type AssessmentRunDuration = number;

    export type AssessmentRunInProgressArnList = Arn[];

    export type AssessmentRunList = AssessmentRun[];

    export type AssessmentRunName = string;

    export type AssessmentRunNotificationList = AssessmentRunNotification[];

    export type AssessmentRunNotificationSnsStatusCode = string;

    export type AssessmentRunState = string;

    export type AssessmentRunStateChangeList = AssessmentRunStateChange[];

    export type AssessmentRunStateList = AssessmentRunState[];

    export type AssessmentTargetList = AssessmentTarget[];

    export type AssessmentTargetName = string;

    export type AssessmentTemplateList = AssessmentTemplate[];

    export type AssessmentTemplateName = string;

    export type AssessmentTemplateRulesPackageArnList = Arn[];

    export type AssetType = string;

    export type AttributeKey = string;

    export type AttributeList = Attribute[];

    export type AttributeValue = string;

    export type AutoScalingGroup = string;

    export type AutoScalingGroupList = AutoScalingGroup[];

    export type BatchDescribeArnList = Arn[];

    export type Bool = boolean;

    export type ErrorMessage = string;

    export type EventSubscriptionList = EventSubscription[];

    export type FailedItemErrorCode = string;

    export type FailedItems = { [key: string]: FailedItemDetails };

    export type FilterRulesPackageArnList = Arn[];

    export type FindingId = string;

    export type FindingList = Finding[];

    export type Hostname = string;

    export type InspectorEvent = string;

    export type InvalidCrossAccountRoleErrorCode = string;

    export type InvalidInputErrorCode = string;

    export type IocConfidence = number;

    export type Ipv4Address = string;

    export type Ipv4AddressList = Ipv4Address[];

    export type LimitExceededErrorCode = string;

    export type ListEventSubscriptionsMaxResults = number;

    export type ListMaxResults = number;

    export type ListParentArnList = Arn[];

    export type ListReturnedArnList = Arn[];

    export type Locale = string;

    export type Long = number;

    export type Message = string;

    export type MessageType = string;

    export type NamePattern = string;

    export type NoSuchEntityErrorCode = string;

    export type NumericSeverity = number;

    export type NumericVersion = number;

    export type PaginationToken = string;

    export type PreviewAgentsMaxResults = number;

    export type ProviderName = string;

    export type ResourceGroupList = ResourceGroup[];

    export type ResourceGroupTags = ResourceGroupTag[];

    export type RuleName = string;

    export type RuleNameList = RuleName[];

    export type RulesPackageList = RulesPackage[];

    export type RulesPackageName = string;

    export type ServiceName = string;

    export type Severity = string;

    export type SeverityList = Severity[];

    export type SubscriptionList = Subscription[];

    export type TagKey = string;

    export type TagList = Tag[];

    export type TagValue = string;

    export type TelemetryMetadataList = TelemetryMetadata[];

    export type Text = string;

    export type Timestamp = number;

    export type UserAttributeKeyList = AttributeKey[];

    export type UserAttributeList = Attribute[];

    export type Version = string;

    export interface AccessDeniedException {
      /** Details of the exception error. **/
      message: ErrorMessage;
      /** Code that indicates the type of error that is generated. **/
      errorCode: AccessDeniedErrorCode;
      /** You can immediately retry your request. **/
      canRetry: Bool;
    }
    export interface AddAttributesToFindingsRequest {
      /** The ARNs that specify the findings that you want to assign attributes to. **/
      findingArns: AddRemoveAttributesFindingArnList;
      /** The array of attributes that you want to assign to specified findings. **/
      attributes: UserAttributeList;
    }
    export interface AddAttributesToFindingsResponse {
      /** Attribute details that cannot be described. An error code is provided for each
failed item. **/
      failedItems: FailedItems;
    }
    export interface AgentAlreadyRunningAssessment {
      /** ID of the agent that is running on an EC2 instance that is already participating
in another started assessment run. **/
      agentId: AgentId;
      /** The ARN of the assessment run that has already been started. **/
      assessmentRunArn: Arn;
    }
    export interface AgentFilter {
      /** The current health state of the agent. Values can be set to HEALTHY or UNHEALTHY
. **/
      agentHealths: AgentHealthList;
      /** The detailed health state of the agent. Values can be set to IDLE, RUNNING, 
SHUTDOWN, UNHEALTHY, THROTTLED, and UNKNOWN. **/
      agentHealthCodes: AgentHealthCodeList;
    }
    export interface AgentPreview {
      /** The ID of the EC2 instance where the agent is installed. **/
      agentId: AgentId;
      /** The Auto Scaling group for the EC2 instance where the agent is installed. **/
      autoScalingGroup?: AutoScalingGroup;
    }
    export interface AgentsAlreadyRunningAssessmentException {
      /** Details of the exception error. **/
      message: ErrorMessage;
      /**  **/
      agents: AgentAlreadyRunningAssessmentList;
      /**  **/
      agentsTruncated: Bool;
      /** You can immediately retry your request. **/
      canRetry: Bool;
    }
    export interface AssessmentRun {
      /** The ARN of the assessment run. **/
      arn: Arn;
      /** The auto-generated name for the assessment run. **/
      name: AssessmentRunName;
      /** The ARN of the assessment template that is associated with the assessment run. **/
      assessmentTemplateArn: Arn;
      /** The state of the assessment run. **/
      state: AssessmentRunState;
      /** The duration of the assessment run. **/
      durationInSeconds: AssessmentRunDuration;
      /** The rules packages selected for the assessment run. **/
      rulesPackageArns: AssessmentRulesPackageArnList;
      /** The user-defined attributes that are assigned to every generated finding. **/
      userAttributesForFindings: UserAttributeList;
      /** The time when StartAssessmentRun was called. **/
      createdAt: Timestamp;
      /** The time when StartAssessmentRun was called. **/
      startedAt?: Timestamp;
      /** The assessment run completion time that corresponds to the rules packages
evaluation completion time or failure. **/
      completedAt?: Timestamp;
      /** The last time when the assessment run&#x27;s state changed. **/
      stateChangedAt: Timestamp;
      /** A Boolean value (true or false) that specifies whether the process of collecting
data from the agents is completed. **/
      dataCollected: Bool;
      /** A list of the assessment run state changes. **/
      stateChanges: AssessmentRunStateChangeList;
      /** A list of notifications for the event subscriptions. A notification about a
particular generated finding is added to this list only once. **/
      notifications: AssessmentRunNotificationList;
    }
    export interface AssessmentRunAgent {
      /** The AWS account of the EC2 instance where the agent is installed. **/
      agentId: AgentId;
      /** The ARN of the assessment run that is associated with the agent. **/
      assessmentRunArn: Arn;
      /** The current health state of the agent. **/
      agentHealth: AgentHealth;
      /** The detailed health state of the agent. **/
      agentHealthCode: AgentHealthCode;
      /** The description for the agent health code. **/
      agentHealthDetails?: Message;
      /** The Auto Scaling group of the EC2 instance that is specified by the agent ID. **/
      autoScalingGroup?: AutoScalingGroup;
      /** The Amazon Inspector application data metrics that are collected by the agent. **/
      telemetryMetadata: TelemetryMetadataList;
    }
    export interface AssessmentRunFilter {
      /** For a record to match a filter, an explicit value or a string containing a
wildcard that is specified for this data type property must match the value of
the assessmentRunName property of the AssessmentRun data type. **/
      namePattern?: NamePattern;
      /** For a record to match a filter, one of the values specified for this data type
property must be the exact match of the value of the assessmentRunState property
of the AssessmentRun data type. **/
      states?: AssessmentRunStateList;
      /** For a record to match a filter, the value that is specified for this data type
property must inclusively match any value between the specified minimum and
maximum values of the durationInSeconds property of the AssessmentRun data type. **/
      durationRange?: DurationRange;
      /** For a record to match a filter, the value that is specified for this data type
property must be contained in the list of values of the rulesPackages property
of the AssessmentRun data type. **/
      rulesPackageArns?: FilterRulesPackageArnList;
      /** For a record to match a filter, the value that is specified for this data type
property must inclusively match any value between the specified minimum and
maximum values of the startTime property of the AssessmentRun data type. **/
      startTimeRange?: TimestampRange;
      /** For a record to match a filter, the value that is specified for this data type
property must inclusively match any value between the specified minimum and
maximum values of the completedAt property of the AssessmentRun data type. **/
      completionTimeRange?: TimestampRange;
      /** For a record to match a filter, the value that is specified for this data type
property must match the stateChangedAt property of the AssessmentRun data type. **/
      stateChangeTimeRange?: TimestampRange;
    }
    export interface AssessmentRunInProgressException {
      /** Details of the exception error. **/
      message: ErrorMessage;
      /** The ARNs of the assessment runs that are currently in progress. **/
      assessmentRunArns: AssessmentRunInProgressArnList;
      /** Boolean value that indicates whether the ARN list of the assessment runs is
truncated. **/
      assessmentRunArnsTruncated: Bool;
      /** You can immediately retry your request. **/
      canRetry: Bool;
    }
    export interface AssessmentRunNotification {
      /** The date of the notification. **/
      date: Timestamp;
      /** The event for which a notification is sent. **/
      event: InspectorEvent;
      message?: Message;
      /** The Boolean value that specifies whether the notification represents an error. **/
      error: Bool;
      /** The SNS topic to which the SNS notification is sent. **/
      snsTopicArn?: Arn;
      /** The status code of the SNS notification. **/
      snsPublishStatusCode?: AssessmentRunNotificationSnsStatusCode;
    }
    export interface AssessmentRunStateChange {
      /** The last time the assessment run state changed. **/
      stateChangedAt: Timestamp;
      /** The assessment run state. **/
      state: AssessmentRunState;
    }
    export interface AssessmentTarget {
      /** The ARN that specifies the Amazon Inspector assessment target. **/
      arn: Arn;
      /** The name of the Amazon Inspector assessment target. **/
      name: AssessmentTargetName;
      /** The ARN that specifies the resource group that is associated with the assessment
target. **/
      resourceGroupArn: Arn;
      /** The time at which the assessment target is created. **/
      createdAt: Timestamp;
      /** The time at which UpdateAssessmentTarget is called. **/
      updatedAt: Timestamp;
    }
    export interface AssessmentTargetFilter {
      /** For a record to match a filter, an explicit value or a string that contains a
wildcard that is specified for this data type property must match the value of
the assessmentTargetName property of the AssessmentTarget data type. **/
      assessmentTargetNamePattern?: NamePattern;
    }
    export interface AssessmentTemplate {
      /** The ARN of the assessment template. **/
      arn: Arn;
      /** The name of the assessment template. **/
      name: AssessmentTemplateName;
      /** The ARN of the assessment target that corresponds to this assessment template. **/
      assessmentTargetArn: Arn;
      /** The duration in seconds specified for this assessment tempate. The default value
is 3600 seconds (one hour). The maximum value is 86400 seconds (one day). **/
      durationInSeconds: AssessmentRunDuration;
      /** The rules packages that are specified for this assessment template. **/
      rulesPackageArns: AssessmentTemplateRulesPackageArnList;
      /** The user-defined attributes that are assigned to every generated finding from
the assessment run that uses this assessment template. **/
      userAttributesForFindings: UserAttributeList;
      /** The time at which the assessment template is created. **/
      createdAt: Timestamp;
    }
    export interface AssessmentTemplateFilter {
      /** For a record to match a filter, an explicit value or a string that contains a
wildcard that is specified for this data type property must match the value of
the assessmentTemplateName property of the AssessmentTemplate data type. **/
      namePattern?: NamePattern;
      /** For a record to match a filter, the value specified for this data type property
must inclusively match any value between the specified minimum and maximum
values of the durationInSeconds property of the AssessmentTemplate data type. **/
      durationRange?: DurationRange;
      /** For a record to match a filter, the values that are specified for this data type
property must be contained in the list of values of the rulesPackageArns 
property of the AssessmentTemplate data type. **/
      rulesPackageArns?: FilterRulesPackageArnList;
    }
    export interface AssetAttributes {
      /** The schema version of this data type. **/
      schemaVersion: NumericVersion;
      /** The ID of the agent that is installed on the EC2 instance where the finding is
generated. **/
      agentId?: AgentId;
      /** The Auto Scaling group of the EC2 instance where the finding is generated. **/
      autoScalingGroup?: AutoScalingGroup;
      /** The ID of the Amazon Machine Image (AMI) that is installed on the EC2 instance
where the finding is generated. **/
      amiId?: AmiId;
      /** The hostname of the EC2 instance where the finding is generated. **/
      hostname?: Hostname;
      /** The list of IP v4 addresses of the EC2 instance where the finding is generated. **/
      ipv4Addresses?: Ipv4AddressList;
    }
    export interface Attribute {
      /** The attribute key. **/
      key: AttributeKey;
      /** The value assigned to the attribute key. **/
      value?: AttributeValue;
    }
    export interface CreateAssessmentTargetRequest {
      /** The user-defined name that identifies the assessment target that you want to
create. The name must be unique within the AWS account. **/
      assessmentTargetName: AssessmentTargetName;
      /** The ARN that specifies the resource group that is used to create the assessment
target. **/
      resourceGroupArn: Arn;
    }
    export interface CreateAssessmentTargetResponse {
      /** The ARN that specifies the assessment target that is created. **/
      assessmentTargetArn: Arn;
    }
    export interface CreateAssessmentTemplateRequest {
      /** The ARN that specifies the assessment target for which you want to create the
assessment template. **/
      assessmentTargetArn: Arn;
      /** The user-defined name that identifies the assessment template that you want to
create. You can create several assessment templates for an assessment target.
The names of the assessment templates that correspond to a particular assessment
target must be unique. **/
      assessmentTemplateName: AssessmentTemplateName;
      /** The duration of the assessment run in seconds. The default value is 3600 seconds
(one hour). **/
      durationInSeconds: AssessmentRunDuration;
      /** The ARNs that specify the rules packages that you want to attach to the
assessment template. **/
      rulesPackageArns: AssessmentTemplateRulesPackageArnList;
      /** The user-defined attributes that are assigned to every finding that is generated
by the assessment run that uses this assessment template. **/
      userAttributesForFindings?: UserAttributeList;
    }
    export interface CreateAssessmentTemplateResponse {
      /** The ARN that specifies the assessment template that is created. **/
      assessmentTemplateArn: Arn;
    }
    export interface CreateResourceGroupRequest {
      /** A collection of keys and an array of possible values,
&#x27;[{&quot;key&quot;:&quot;key1&quot;,&quot;values&quot;:[&quot;Value1&quot;,&quot;Value2&quot;]},{&quot;key&quot;:&quot;Key2&quot;,&quot;values&quot;:[&quot;Value3&quot;]}]&#x27;.

For example,&#x27;[{&quot;key&quot;:&quot;Name&quot;,&quot;values&quot;:[&quot;TestEC2Instance&quot;]}]&#x27;. **/
      resourceGroupTags: ResourceGroupTags;
    }
    export interface CreateResourceGroupResponse {
      /** The ARN that specifies the resource group that is created. **/
      resourceGroupArn: Arn;
    }
    export interface DeleteAssessmentRunRequest {
      /** The ARN that specifies the assessment run that you want to delete. **/
      assessmentRunArn: Arn;
    }
    export interface DeleteAssessmentTargetRequest {
      /** The ARN that specifies the assessment target that you want to delete. **/
      assessmentTargetArn: Arn;
    }
    export interface DeleteAssessmentTemplateRequest {
      /** The ARN that specifies the assessment template that you want to delete. **/
      assessmentTemplateArn: Arn;
    }
    export interface DescribeAssessmentRunsRequest {
      /** The ARN that specifies the assessment run that you want to describe. **/
      assessmentRunArns: BatchDescribeArnList;
    }
    export interface DescribeAssessmentRunsResponse {
      /** Information about the assessment run. **/
      assessmentRuns: AssessmentRunList;
      /** Assessment run details that cannot be described. An error code is provided for
each failed item. **/
      failedItems: FailedItems;
    }
    export interface DescribeAssessmentTargetsRequest {
      /** The ARNs that specifies the assessment targets that you want to describe. **/
      assessmentTargetArns: BatchDescribeArnList;
    }
    export interface DescribeAssessmentTargetsResponse {
      /** Information about the assessment targets. **/
      assessmentTargets: AssessmentTargetList;
      /** Assessment target details that cannot be described. An error code is provided
for each failed item. **/
      failedItems: FailedItems;
    }
    export interface DescribeAssessmentTemplatesRequest {
      /** The ARN that specifiesthe assessment templates that you want to describe. **/
      assessmentTemplateArns: BatchDescribeArnList;
    }
    export interface DescribeAssessmentTemplatesResponse {
      /** Information about the assessment templates. **/
      assessmentTemplates: AssessmentTemplateList;
      /** Assessment template details that cannot be described. An error code is provided
for each failed item. **/
      failedItems: FailedItems;
    }
    export interface DescribeCrossAccountAccessRoleResponse {
      /** The ARN that specifies the IAM role that Amazon Inspector uses to access your
AWS account. **/
      roleArn: Arn;
      /** A Boolean value that specifies whether the IAM role has the necessary policies
attached to enable Amazon Inspector to access your AWS account. **/
      valid: Bool;
      /** The date when the cross-account access role was registered. **/
      registeredAt: Timestamp;
    }
    export interface DescribeFindingsRequest {
      /** The ARN that specifies the finding that you want to describe. **/
      findingArns: BatchDescribeArnList;
      /** The locale into which you want to translate a finding description,
recommendation, and the short description that identifies the finding. **/
      locale?: Locale;
    }
    export interface DescribeFindingsResponse {
      /** Information about the finding. **/
      findings: FindingList;
      /** Finding details that cannot be described. An error code is provided for each
failed item. **/
      failedItems: FailedItems;
    }
    export interface DescribeResourceGroupsRequest {
      /** The ARN that specifies the resource group that you want to describe. **/
      resourceGroupArns: BatchDescribeArnList;
    }
    export interface DescribeResourceGroupsResponse {
      /** Information about a resource group. **/
      resourceGroups: ResourceGroupList;
      /** Resource group details that cannot be described. An error code is provided for
each failed item. **/
      failedItems: FailedItems;
    }
    export interface DescribeRulesPackagesRequest {
      /** The ARN that specifies the rules package that you want to describe. **/
      rulesPackageArns: BatchDescribeArnList;
      /** The locale that you want to translate a rules package description into. **/
      locale?: Locale;
    }
    export interface DescribeRulesPackagesResponse {
      /** Information about the rules package. **/
      rulesPackages: RulesPackageList;
      /** Rules package details that cannot be described. An error code is provided for
each failed item. **/
      failedItems: FailedItems;
    }
    export interface DurationRange {
      /** The minimum value of the duration range. Must be greater than zero. **/
      minSeconds?: AssessmentRunDuration;
      /** The maximum value of the duration range. Must be less than or equal to 604800
seconds (1 week). **/
      maxSeconds?: AssessmentRunDuration;
    }
    export interface EventSubscription {
      /** The event for which Amazon Simple Notification Service (SNS) notifications are
sent. **/
      event: InspectorEvent;
      /** The time at which SubscribeToEvent is called. **/
      subscribedAt: Timestamp;
    }
    export interface FailedItemDetails {
      /** The status code of a failed item. **/
      failureCode: FailedItemErrorCode;
      /** Indicates whether you can immediately retry a request for this item for a
specified resource. **/
      retryable: Bool;
    }
    export interface Finding {
      /** The ARN that specifies the finding. **/
      arn: Arn;
      /** The schema version of this data type. **/
      schemaVersion?: NumericVersion;
      /** The data element is set to &quot;Inspector&quot;. **/
      service?: ServiceName;
      serviceAttributes?: InspectorServiceAttributes;
      /** The type of the host from which the finding is generated. **/
      assetType?: AssetType;
      /** A collection of attributes of the host from which the finding is generated. **/
      assetAttributes?: AssetAttributes;
      /** The ID of the finding. **/
      id?: FindingId;
      /** The name of the finding. **/
      title?: Text;
      /** The description of the finding. **/
      description?: Text;
      /** The recommendation for the finding. **/
      recommendation?: Text;
      /** The finding severity. Values can be set to High, Medium, Low, and Informational. **/
      severity?: Severity;
      /** The numeric value of the finding severity. **/
      numericSeverity?: NumericSeverity;
      /** This data element is currently not used. **/
      confidence?: IocConfidence;
      /** This data element is currently not used. **/
      indicatorOfCompromise?: Bool;
      /** The system-defined attributes for the finding. **/
      attributes: AttributeList;
      /** The user-defined attributes that are assigned to the finding. **/
      userAttributes: UserAttributeList;
      /** The time when the finding was generated. **/
      createdAt: Timestamp;
      /** The time when AddAttributesToFindings is called. **/
      updatedAt: Timestamp;
    }
    export interface FindingFilter {
      /** For a record to match a filter, one of the values that is specified for this
data type property must be the exact match of the value of the agentId property
of the Finding data type. **/
      agentIds?: AgentIdList;
      /** For a record to match a filter, one of the values that is specified for this
data type property must be the exact match of the value of the autoScalingGroup 
property of the Finding data type. **/
      autoScalingGroups?: AutoScalingGroupList;
      /** For a record to match a filter, one of the values that is specified for this
data type property must be the exact match of the value of the ruleName property
of the Finding data type. **/
      ruleNames?: RuleNameList;
      /** For a record to match a filter, one of the values that is specified for this
data type property must be the exact match of the value of the severity property
of the Finding data type. **/
      severities?: SeverityList;
      /** For a record to match a filter, one of the values that is specified for this
data type property must be the exact match of the value of the rulesPackageArn 
property of the Finding data type. **/
      rulesPackageArns?: FilterRulesPackageArnList;
      /** For a record to match a filter, the list of values that are specified for this
data type property must be contained in the list of values of the attributes 
property of the Finding data type. **/
      attributes?: AttributeList;
      /** For a record to match a filter, the value that is specified for this data type
property must be contained in the list of values of the userAttributes property
of the Finding data type. **/
      userAttributes?: AttributeList;
      /** The time range during which the finding is generated. **/
      creationTimeRange?: TimestampRange;
    }
    export interface GetTelemetryMetadataRequest {
      /** The ARN that specifies the assessment run that has the telemetry data that you
want to obtain. **/
      assessmentRunArn: Arn;
    }
    export interface GetTelemetryMetadataResponse {
      /** Telemetry details. **/
      telemetryMetadata: TelemetryMetadataList;
    }
    export interface InspectorServiceAttributes {
      /** The schema version of this data type. **/
      schemaVersion: NumericVersion;
      /** The ARN of the assessment run during which the finding is generated. **/
      assessmentRunArn?: Arn;
      /** The ARN of the rules package that is used to generate the finding. **/
      rulesPackageArn?: Arn;
    }
    export interface InternalException {
      /** Details of the exception error. **/
      message: ErrorMessage;
      /** You can immediately retry your request. **/
      canRetry: Bool;
    }
    export interface InvalidCrossAccountRoleException {
      /** Details of the exception error. **/
      message: ErrorMessage;
      /** Code that indicates the type of error that is generated. **/
      errorCode: InvalidCrossAccountRoleErrorCode;
      /** You can immediately retry your request. **/
      canRetry: Bool;
    }
    export interface InvalidInputException {
      /** Details of the exception error. **/
      message: ErrorMessage;
      /** Code that indicates the type of error that is generated. **/
      errorCode: InvalidInputErrorCode;
      /** You can immediately retry your request. **/
      canRetry: Bool;
    }
    export interface LimitExceededException {
      /** Details of the exception error. **/
      message: ErrorMessage;
      /** Code that indicates the type of error that is generated. **/
      errorCode: LimitExceededErrorCode;
      /** You can immediately retry your request. **/
      canRetry: Bool;
    }
    export interface ListAssessmentRunAgentsRequest {
      /** The ARN that specifies the assessment run whose agents you want to list. **/
      assessmentRunArn: Arn;
      /** You can use this parameter to specify a subset of data to be included in the
action&#x27;s response.

For a record to match a filter, all specified filter attributes must match. When
multiple values are specified for a filter attribute, any of the values can
match. **/
      filter?: AgentFilter;
      /** You can use this parameter when paginating results. Set the value of this
parameter to null on your first call to the ListAssessmentRunAgents action.
Subsequent calls to the action fill nextToken in the request with the value of 
NextToken from the previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items that you want
in the response. The default value is 10. The maximum value is 500. **/
      maxResults?: ListMaxResults;
    }
    export interface ListAssessmentRunAgentsResponse {
      /** A list of ARNs that specifies the agents returned by the action. **/
      assessmentRunAgents: AssessmentRunAgentList;
      /** When a response is generated, if there is more data to be listed, this
parameter is present in the response and contains the value to use for the 
nextToken parameter in a subsequent pagination request. If there is no more data
to be listed, this parameter is set to null. **/
      nextToken?: PaginationToken;
    }
    export interface ListAssessmentRunsRequest {
      /** The ARNs that specify the assessment templates whose assessment runs you want to
list. **/
      assessmentTemplateArns?: ListParentArnList;
      /** You can use this parameter to specify a subset of data to be included in the
action&#x27;s response.

For a record to match a filter, all specified filter attributes must match. When
multiple values are specified for a filter attribute, any of the values can
match. **/
      filter?: AssessmentRunFilter;
      /** You can use this parameter when paginating results. Set the value of this
parameter to null on your first call to the ListAssessmentRuns action.
Subsequent calls to the action fill nextToken in the request with the value of 
NextToken from the previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items that you want
in the response. The default value is 10. The maximum value is 500. **/
      maxResults?: ListMaxResults;
    }
    export interface ListAssessmentRunsResponse {
      /** A list of ARNs that specifies the assessment runs that are returned by the
action. **/
      assessmentRunArns: ListReturnedArnList;
      /** When a response is generated, if there is more data to be listed, this
parameter is present in the response and contains the value to use for the 
nextToken parameter in a subsequent pagination request. If there is no more data
to be listed, this parameter is set to null. **/
      nextToken?: PaginationToken;
    }
    export interface ListAssessmentTargetsRequest {
      /** You can use this parameter to specify a subset of data to be included in the
action&#x27;s response.

For a record to match a filter, all specified filter attributes must match. When
multiple values are specified for a filter attribute, any of the values can
match. **/
      filter?: AssessmentTargetFilter;
      /** You can use this parameter when paginating results. Set the value of this
parameter to null on your first call to the ListAssessmentTargets action.
Subsequent calls to the action fill nextToken in the request with the value of 
NextToken from the previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: ListMaxResults;
    }
    export interface ListAssessmentTargetsResponse {
      /** A list of ARNs that specifies the assessment targets that are returned by the
action. **/
      assessmentTargetArns: ListReturnedArnList;
      /** When a response is generated, if there is more data to be listed, this
parameter is present in the response and contains the value to use for the 
nextToken parameter in a subsequent pagination request. If there is no more data
to be listed, this parameter is set to null. **/
      nextToken?: PaginationToken;
    }
    export interface ListAssessmentTemplatesRequest {
      /** A list of ARNs that specifies the assessment targets whose assessment templates
you want to list. **/
      assessmentTargetArns?: ListParentArnList;
      /** You can use this parameter to specify a subset of data to be included in the
action&#x27;s response.

For a record to match a filter, all specified filter attributes must match. When
multiple values are specified for a filter attribute, any of the values can
match. **/
      filter?: AssessmentTemplateFilter;
      /** You can use this parameter when paginating results. Set the value of this
parameter to null on your first call to the ListAssessmentTemplates action.
Subsequent calls to the action fill nextToken in the request with the value of 
NextToken from the previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: ListMaxResults;
    }
    export interface ListAssessmentTemplatesResponse {
      /** A list of ARNs that specifies the assessment templates returned by the action. **/
      assessmentTemplateArns: ListReturnedArnList;
      /** When a response is generated, if there is more data to be listed, this
parameter is present in the response and contains the value to use for the 
nextToken parameter in a subsequent pagination request. If there is no more data
to be listed, this parameter is set to null. **/
      nextToken?: PaginationToken;
    }
    export interface ListEventSubscriptionsRequest {
      /** The ARN of the assessment template for which you want to list the existing event
subscriptions. **/
      resourceArn?: Arn;
      /** You can use this parameter when paginating results. Set the value of this
parameter to null on your first call to the ListEventSubscriptions action.
Subsequent calls to the action fill nextToken in the request with the value of 
NextToken from the previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: ListEventSubscriptionsMaxResults;
    }
    export interface ListEventSubscriptionsResponse {
      /** Details of the returned event subscriptions. **/
      subscriptions: SubscriptionList;
      /** When a response is generated, if there is more data to be listed, this
parameter is present in the response and contains the value to use for the 
nextToken parameter in a subsequent pagination request. If there is no more data
to be listed, this parameter is set to null. **/
      nextToken?: PaginationToken;
    }
    export interface ListFindingsRequest {
      /** The ARNs of the assessment runs that generate the findings that you want to
list. **/
      assessmentRunArns?: ListParentArnList;
      /** You can use this parameter to specify a subset of data to be included in the
action&#x27;s response.

For a record to match a filter, all specified filter attributes must match. When
multiple values are specified for a filter attribute, any of the values can
match. **/
      filter?: FindingFilter;
      /** You can use this parameter when paginating results. Set the value of this
parameter to null on your first call to the ListFindings action. Subsequent
calls to the action fill nextToken in the request with the value of NextToken 
from the previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: ListMaxResults;
    }
    export interface ListFindingsResponse {
      /** A list of ARNs that specifies the findings returned by the action. **/
      findingArns: ListReturnedArnList;
      /** When a response is generated, if there is more data to be listed, this
parameter is present in the response and contains the value to use for the 
nextToken parameter in a subsequent pagination request. If there is no more data
to be listed, this parameter is set to null. **/
      nextToken?: PaginationToken;
    }
    export interface ListRulesPackagesRequest {
      /** You can use this parameter when paginating results. Set the value of this
parameter to null on your first call to the ListRulesPackages action. Subsequent
calls to the action fill nextToken in the request with the value of NextToken 
from the previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: ListMaxResults;
    }
    export interface ListRulesPackagesResponse {
      /** The list of ARNs that specifies the rules packages returned by the action. **/
      rulesPackageArns: ListReturnedArnList;
      /** When a response is generated, if there is more data to be listed, this
parameter is present in the response and contains the value to use for the 
nextToken parameter in a subsequent pagination request. If there is no more data
to be listed, this parameter is set to null. **/
      nextToken?: PaginationToken;
    }
    export interface ListTagsForResourceRequest {
      /** The ARN that specifies the assessment template whose tags you want to list. **/
      resourceArn: Arn;
    }
    export interface ListTagsForResourceResponse {
      /** A collection of key and value pairs. **/
      tags: TagList;
    }
    export interface NoSuchEntityException {
      /** Details of the exception error. **/
      message: ErrorMessage;
      /** Code that indicates the type of error that is generated. **/
      errorCode: NoSuchEntityErrorCode;
      /** You can immediately retry your request. **/
      canRetry: Bool;
    }
    export interface PreviewAgentsRequest {
      /** The ARN of the assessment target whose agents you want to preview. **/
      previewAgentsArn: Arn;
      /** You can use this parameter when paginating results. Set the value of this
parameter to null on your first call to the PreviewAgents action. Subsequent
calls to the action fill nextToken in the request with the value of NextToken 
from the previous response to continue listing data. **/
      nextToken?: PaginationToken;
      /** You can use this parameter to indicate the maximum number of items you want in
the response. The default value is 10. The maximum value is 500. **/
      maxResults?: PreviewAgentsMaxResults;
    }
    export interface PreviewAgentsResponse {
      /** The resulting list of agents. **/
      agentPreviews: AgentPreviewList;
      /** When a response is generated, if there is more data to be listed, this
parameter is present in the response and contains the value to use for the 
nextToken parameter in a subsequent pagination request. If there is no more data
to be listed, this parameter is set to null. **/
      nextToken?: PaginationToken;
    }
    export interface RegisterCrossAccountAccessRoleRequest {
      /** The ARN of the IAM role that Amazon Inspector uses to list your EC2 instances
during the assessment run or when you call the PreviewAgents action. **/
      roleArn: Arn;
    }
    export interface RemoveAttributesFromFindingsRequest {
      /** The ARNs that specify the findings that you want to remove attributes from. **/
      findingArns: AddRemoveAttributesFindingArnList;
      /** The array of attribute keys that you want to remove from specified findings. **/
      attributeKeys: UserAttributeKeyList;
    }
    export interface RemoveAttributesFromFindingsResponse {
      /** Attributes details that cannot be described. An error code is provided for each
failed item. **/
      failedItems: FailedItems;
    }
    export interface ResourceGroup {
      /** The ARN of the resource group. **/
      arn: Arn;
      /** The tags (key and value pairs) of the resource group. This data type property is
used in the CreateResourceGroup action. **/
      tags: ResourceGroupTags;
      /** The time at which resource group is created. **/
      createdAt: Timestamp;
    }
    export interface ResourceGroupTag {
      /** A tag key. **/
      key: TagKey;
      /** The value assigned to a tag key. **/
      value?: TagValue;
    }
    export interface RulesPackage {
      /** The ARN of the rules package. **/
      arn: Arn;
      /** The name of the rules package. **/
      name: RulesPackageName;
      /** The version ID of the rules package. **/
      version: Version;
      /** The provider of the rules package. **/
      provider: ProviderName;
      /** The description of the rules package. **/
      description?: Text;
    }
    export interface SetTagsForResourceRequest {
      /** The ARN of the assessment template that you want to set tags to. **/
      resourceArn: Arn;
      /** A collection of key and value pairs that you want to set to the assessment
template. **/
      tags?: TagList;
    }
    export interface StartAssessmentRunRequest {
      /** The ARN of the assessment template of the assessment run that you want to start. **/
      assessmentTemplateArn: Arn;
      /** You can specify the name for the assessment run, or you can use the
auto-generated name that is based on the assessment template name. The name must
be unique for the assessment template. **/
      assessmentRunName?: AssessmentRunName;
    }
    export interface StartAssessmentRunResponse {
      /** The ARN of the assessment run that has been started. **/
      assessmentRunArn: Arn;
    }
    export interface StopAssessmentRunRequest {
      /** The ARN of the assessment run that you want to stop. **/
      assessmentRunArn: Arn;
    }
    export interface SubscribeToEventRequest {
      /** The ARN of the assessment template that is used during the event for which you
want to receive SNS notifications. **/
      resourceArn: Arn;
      /** The event for which you want to receive SNS notifications. **/
      event: InspectorEvent;
      /** The ARN of the SNS topic to which the SNS notifications are sent. **/
      topicArn: Arn;
    }
    export interface Subscription {
      /** The ARN of the assessment template that is used during the event for which the
SNS notification is sent. **/
      resourceArn: Arn;
      /** The ARN of the Amazon Simple Notification Service (SNS) topic to which the SNS
notifications are sent. **/
      topicArn: Arn;
      /** The list of existing event subscriptions. **/
      eventSubscriptions: EventSubscriptionList;
    }
    export interface Tag {
      /** A tag key. **/
      key: TagKey;
      /** A value assigned to a tag key. **/
      value?: TagValue;
    }
    export interface TelemetryMetadata {
      /** A specific type of behavioral data that is collected by the agent. **/
      messageType: MessageType;
      /** The count of messages that the agent sends to the Amazon Inspector service. **/
      count: Long;
      /** The data size of messages that the agent sends to the Amazon Inspector service. **/
      dataSize?: Long;
    }
    export interface TimestampRange {
      /** The minimum value of the timestamp range. **/
      beginDate?: Timestamp;
      /** The maximum value of the timestamp range. **/
      endDate?: Timestamp;
    }
    export interface UnsubscribeFromEventRequest {
      /** The ARN of the assessment template that is used during the event for which you
want to stop receiving SNS notifications. **/
      resourceArn: Arn;
      /** The event for which you want to stop receiving SNS notifications. **/
      event: InspectorEvent;
      /** The ARN of the SNS topic to which SNS notifications are sent. **/
      topicArn: Arn;
    }
    export interface UpdateAssessmentTargetRequest {
      /** The ARN of the assessment target that you want to update. **/
      assessmentTargetArn: Arn;
      /** The name of the assessment target that you want to update. **/
      assessmentTargetName: AssessmentTargetName;
      /** The ARN of the resource group that is used to specify the new resource group to
associate with the assessment target. **/
      resourceGroupArn: Arn;
    }
  }
}
